# Fluxo de trabalho para implantar conteúdo estático no GitHub Pages
name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04  # Mais estável que a 24.04, evita bugs

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Fazer upload do artefato para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # Pasta onde está o seu index.html

      - name: Implantar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
