# Fluxo de trabalho simples para implantar conteúdo estático no GitHub Pages
name: Deploy para GitHub Pages

on:
  # Executa quando há envios direcionados para o branch padrão
  push:
    branches: ["main"]

  # Permite executar este fluxo de trabalho manualmente na aba "Actions"
  workflow_dispatch:

# Define as permissões do GITHUB_TOKEN para permitir implantação no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação simultânea
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Único trabalho de implantação
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Páginas
        uses: actions/configure-pages@v4

      - name: Upload do artefato para GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: Implantação no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3