# Fluxo de trabalho para implantar conteúdo estático no GitHub Pages
name: Deploy GitHub Pages

on:
  # Gatilhos automáticos para o workflow
  push:
    branches: ["main"]
  workflow_dispatch:

# Definindo permissões para o GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Configuração de execução simultânea
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Fazer upload do artefato
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: Implantar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
